export const getProductImageUrl = (image) => {
  const placeholder = '/coffe.jpg';
  if (!image) return placeholder;

  const trimmedImage = typeof image === 'string' ? image.trim() : '';
  if (!trimmedImage) return placeholder;
  if (trimmedImage.startsWith('http://') || trimmedImage.startsWith('https://')) {
    return trimmedImage;
  }

  // Check if it's an uploaded image (starts with a timestamp prefix generated by Multer)
  const isUploaded = /^\d+-/.test(trimmedImage);
  if (isUploaded) {
    const backendUrl = import.meta.env.VITE_API_URL || 'http://localhost:5000';
    return `${backendUrl}/uploads/${trimmedImage}`;
  }

  // Use public root asset path for product image names.
  return `/${encodeURIComponent(trimmedImage)}`;
};
